DROP TABLE IF EXISTS users;

CREATE TABLE if NOT EXISTS users (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(30) NOT NULL,
    lastname VARCHAR(30) NOT NULL,
    dob DATE NOT NULL,
    gender TINYINT(1) NOT NULL, -- 1 for male, 0 for female
    email VARCHAR(50),
    phone VARCHAR(15),
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    money VARCHAR(15) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)